### ISSUE TITLE
Support for Builders

### ISSUE THREAD

**Issue by Wulfheart** [regnerisch/laravel-beyond#12]
Laravel Beyond Crud has the concept of Builders. They aren’t yet implemented I think as the query command of this package is for another things, isn’t it?

**Comment by alexgaal** [comment]
Hi,

it's funny since @regnerisch and I talked about this feature yesterday. It will be implemented within the next week. Thank you for your contribution!

**Comment by regnerisch** [comment]
Version 2.4.0 now supports commands for eloquent query builders, jobs and collections.

**Comment by Wulfheart** [comment]
@regnerisch maybe the builder command should also be in the readme.

**Comment by regnerisch** [comment]
@Wulfheart, it is ;)

`php artisan beyond:make:query-builder Domain/ModelQueryBuilder`
