### ISSUE TITLE
Command for creating domain

### ISSUE THREAD

**Issue by alexanderkroneis** [regnerisch/laravel-beyond#20]
A command which creates every part of a domain would be appreciated.

**Signature**
`beyond:make:module {--model} {--controller} {--policy} {--request} {--resource}`

**Behaviour**
- `beyond:make:module` creates every related file for a domain (model, controller, policy, ...).
- `beyond:make:module --model ...` only creates the model of the domain

**Comment by alexgaal** [comment]
@regnerisch @nilsvennemann What do you think: Shall we close this issue since I actually never missed this functionality?
