### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by Wulfheart** [regnerisch/laravel-beyond#37]
They are not part of the Laravel beyond crud book but Ryutu Hamasaki outlined them in his talk at Laracon Online Winter 2022 (https://youtu.be/0Rq-yHAwYjQ?t=5585). Maybe they are a concept worth adding to the commands (even though they can also be added manually).

**Comment by regnerisch** [comment]
Sorry but I don't get the point, what those contracs are. Could you give us some more information?

**Comment by alexgaal** [comment]
I'll close this issue since no further information were provided.
