### ISSUE TITLE
[3.x] Alternative way to execute commands

### ISSUE THREAD

**Issue by alexgaal** [regnerisch/laravel-beyond#39]
Currently commands are restricted to `beyond:make:command {schema}`. We should provide an alternative way since not everybody is used to "Laravel Beyond CRUD" and may not know the schema.

- `php artisan beyond:make:model` should ask for `Domain` and `Class Name` and creates a class based on these information

**Comment by Wulfheart** [comment]
This could be also enhanced with [autocompletion](https://laravel.com/docs/9.x/artisan#auto-completion) or [multiple choice questions](https://laravel.com/docs/9.x/artisan#multiple-choice-questions) based on the existig `Domains` and `Apps`.

**Comment by alexgaal** [comment]
Thank you for your contribution. We also thinking about these two options. 🙌

**Comment by alexgaal** [comment]
@regnerisch I did not find any issues in beta version. I think we are ready to publish and close this issue.

**Comment by regnerisch** [comment]
I would like to do a final test and also solve #35.

**Comment by alexgaal** [comment]
This will be implemented in 3.0.0.
