### ISSUE TITLE
More info regarding Support/Packages/Laravel

### ISSUE THREAD

**Issue by thewebartisan7** [regnerisch/laravel-beyond#56]
I read only the free blog of laravel beyond, so maybe this is explained in the paid book.

I see that we can use flag `--support` for middleware and rule, and this add them inside `Support/Packages/Laravel`.

For example if I create a middleware with `--support` this is created in:

`Support/Packages/Laravel/Middleware`

Why inside "Laravel" folder and not in Support/Middleware?

Also there is already a folder `Support/Packages/Laravel/Middlewares` (with final "s"), while our middleware is created inside  `Support/Packages/Laravel/Middleware` (without "s").

As I can read about Support namespace in the blog article "as the dumping ground for all little helpers that don't belong anywhere". So not sure why everything it's under "Support/Packages/Laravel" and not directly inside "Support/Middleware", etc..

Not sure if for questions like this there is another place.

Thanks

**Comment by regnerisch** [comment]
First: That additional `s` on `Middleware` is a bug an should not be there. 

Second: I faced a problem with packages and namings. Imagin you install to packages: Package One, which brings custom validation rules and package two which brings rules for something not related to Laravel rules. 

Now you will add a custom validation rule - extending an existing one from package one. You will put them inside `Support/Rules`. Adding a "rule" for package two inside the same directory require you (or your team) to remember which rule you can use as e.g. validation rule inside of Laravel or as rule for package two. 

So I decided to keep things inside `Support/Packages/{PackageName}/{CustomName}/{Classname}`. That is the only reason why things with the `support` flag will be added inside this special namespace. 

I'm open to other ideas.

**Comment by thewebartisan7** [comment]
I think that I got your point, however, for a Support/Rules or any other Support class that it's not of a package, by default it's added inside Support/Packages/Laravel which you may think that it's something of Laravel and not of your app.

Why not just leave the choice to developers how to structure the Support folder?

I mean that via command line you can specify the namespace you wish. When you need to extend a class from a package, you decide to put this inside Support/Packages/Packages/...

I didn't think about extending a package class, but immediately I think about how Laravel handle the views that you can extend of a packages. Everything is added inside views/vendor folder.

Which is similar to your solution, but you named it "Packages" instead of Vendor.

So that it's good. But let's leave this choice to developer, maybe by asking via command line like you did for app and domain.

**Comment by regnerisch** [comment]
I will talk with @alexgaal and we may revert this again. :) Thanks for the input

**Comment by regnerisch** [comment]
Fixed in #71
