### ISSUE TITLE
Missing ViewModels

### ISSUE THREAD

**Issue by thewebartisan7** [regnerisch/laravel-beyond#57]
Is there a reason why you don't add ViewModels using the same Spatie package?

**Comment by regnerisch** [comment]
I never used ViewModels. I designed an API when I started developing this package, so I never thought of adding ist. Feel free to add ViewModels as I think this will be useful for many people!

**Comment by thewebartisan7** [comment]
Ok, I will in next days.

**Comment by thewebartisan7** [comment]
Here is https://github.com/regnerisch/laravel-beyond/pull/59

You make super simple create new command :=)
