### ISSUE TITLE
Laravel action queueable package

### ISSUE THREAD

**Issue by thewebartisan7** [regnerisch/laravel-beyond#62]
Would you be interested in adding this package for action:

https://github.com/spatie/laravel-queueable-action

As replacement for current `MakeActionCommand`, or as a new one.

Command signature would be:

`beyond:make:qa {name?} {--overwrite} {--queueable}`

or in case as replacement for current Action:

`beyond:make:action {name?} {--overwrite} {--queueable}`

I am tempted also by this package https://laravelactions.com/ but maybe it's too much, even if can be cherry pick what you want from it, https://laravelactions.com/2.x/granular-traits.html#cherry-picking

Also not sure how if this can be even combined with DDD.

What you think?

**Comment by regnerisch** [comment]
Adding a flag for queueable actions is not a bad idea. I would like to keep the existing `beyond:make:action` command for that. Feel free to add an pull request, but keep in mind to ensure the user can only execute the flag if the required package is installed.

**Comment by thewebartisan7** [comment]
Great, I will check into in next days.

**Comment by thewebartisan7** [comment]
This is added. For ensure that the required package is installed only when using option --queueable, I don't see better way to do so apart overriding execute() method in the command, since execute is called before handle().

```php
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        if ($this->option('queueable')) {
            $this->requiredPackages = [
                'spatie/laravel-queueable-action',
            ];
        }

        return parent::execute($input, $output);
    }
```

**Comment by regnerisch** [comment]
Maybe we can develop a better solution in v4.
