### ISSUE TITLE
Setup needs manual adding of code

### ISSUE THREAD

**Issue by Wulfheart** [regnerisch/laravel-beyond#68]
Hello,

when setting up the project I get the prompt to add something to the boot method of my AppServiceProvider.
1. Which exact namespace is this `Factory`? There are multiple ones provided by Laravel.
2. Why is this not automatically added?

![image](https://user-images.githubusercontent.com/25671390/189551225-20a64df1-52bd-4132-95c7-0abf0801a5c2.png)

**Comment by regnerisch** [comment]
This code ensures the functionality of model factories. Without this added in `AppServiceProvider` you would get an error inside your tests/ seeders as the factory would not be found (`User::factory()`).

We do not add this automatically as we do not know if the user uses spaces or tabs and we need to add this inside the boot function and we do not want to break something inside if it was already customized. 

If you have a possible solution for us, feel free to add an PR. :)

**Comment by Wulfheart** [comment]
Thanks for your response. I am going to give it a shot later.

Just for clarification:

> we do not know if the user uses spaces or tabs 

How do you handle this then when generating a file? I assume it should also be an issue there.

**Comment by regnerisch** [comment]
That's a point, stubs use tabs. You are right, this argument is not really good.

**Comment by Wulfheart** [comment]
I am going to open a PR then.
