### ISSUE TITLE
Architectural design question

### ISSUE THREAD

**Issue by Wulfheart** [regnerisch/laravel-beyond#69]
Hello,

currently I am planning an application and I am unsure about the separation of the domains. 

For example I have a `Game` domain for playing the games and a `Ranking` domain which is event-sourced and is responsible for interacting with an external API to determine it. I plan that the communication between these domains is going to happen using Events. However, to display the leader board to I want to have the user name and the corresponding rank. I understand that this is done using `Model` relationships. In that case there would be a cross-domain relationship which does not feel very clean to me as the separation gets blurred on the data layer. 

Do you have any suggestion how I can solve this?

Thank you in advance!

**Comment by regnerisch** [comment]
I'm pretty sure it is not possible to seperate models and relation-models, as this is an Laravel specific thing. Also this is not the goal of this package. We want to help people setting up an DDD application as easy as possible, you are still free to implement things as you want - sperate code strict by domains or mix up everything. But of course you are welcome to share a possible solution with us as soon as you developed it. :) I would be interessted if it would be possible to sperate models and relation-models and how to do it.

**Comment by Wulfheart** [comment]
Thanks for your response. 

I've since come to the realization that the domains aren't there for strict separation so that I can later transition the domains into individual microservices if needed, but rather a way to organize code. It’s like a mental model.
